services:
  - type: web
    name: oceanos-chat
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
